# Generated by Django 4.2.25 on 2025-11-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_featured_image_event_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
